apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ cookiecutter.dns_slug }}
  labels:
    app: {{ cookiecutter.dns_slug }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ cookiecutter.dns_slug }}
    spec:
      containers:
      - name: {{ cookiecutter.dns_slug }}
        image: '{{ cookiecutter.dns_slug }}:v1'
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_CONFIG
          value: "development"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: host
        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: db_name
      restartPolicy: Always
